version: "3"

# Specifically for kubernetes

services:

  mysqldb-docker:
    image: mysql:8.0
    container_name: mysqldb
    networks:
      - app-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flight_booking
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql

  user-service:
    image: user-service:1.0
    build:
      context: ./UserService
    container_name: user-service
    ports:
      - "8081:8080"
    networks:
      - app-mysql
    depends_on:
      - mysqldb-docker
    environment:
      - SPRING_DATASOURCE_DB_HOST=mysqldb
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/flight_booking?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  flight-service:
    image: flight-service
    build:
      context: ./FlightService
    container_name: flight-service
    ports:
      - "8082:8080"
    networks:
      - app-mysql
    depends_on:
      - mysqldb-docker
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/flight_booking?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  booking-service:
    image: booking-service
    build:
      context: ./BookingService
    container_name: booking-service
    ports:
      - "8083:8080"
    networks:
      - app-mysql
    depends_on:
      - mysqldb-docker
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/flight_booking?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

# Volumes
volumes:
  mysqldb-docker:

networks:
  app-mysql:
