apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Must match the access mode in the PV
  resources:
    requests:
      storage: 5Gi  # Must match the storage size in the PV
