apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1  # Set the desired number of replicas
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: sweetyrv/flight_booking:user-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_DATABASE
              value: flight_booking
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_DB_HOST
              value: mysqldb-service
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqldb-service:3306/flight_booking?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
      # Add any necessary volume mounts or other configuration here
